cc_library(
    name = "hello_world_lib",
    srcs = glob(["hello_world.cc"]),
    hdrs = glob(["hello_world.h"]),
    visibility = ["//visibility:public"],
)

cc_library(
  name = "scsi_defs_lib",
  hdrs = ["scsi_defs.h"],
  visibility = ["//visibility:public"],
)
