cc_library(
    name = "hello_world_lib",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
)

cc_library(
  name = "scsi_defs_lib",
  hdrs = ["scsi_defs.h"],
  visibility = ["//visibility:public"],
)
