cc_library(
    name = "hello_world_lib",
    srcs = ["hello_world.cc"],
    hdrs = ["hello_world.h"],
    visibility = ["//visibility:public"],
)

cc_library(
  name = "scsi_defs_lib",
  hdrs = ["scsi_defs.h"],
  deps = ["@com_google_absl//absl/base"],
  visibility = ["//visibility:public"],
)
