cc_test(
    name = "read_capacity_10_tests",
    srcs = ["read_capacity_10_test.cc"],
    deps = [
        "//lib/translator:read_capacity_10_lib",
        "@googletest//:gtest_main"
    ]
)

cc_test(
  name = "maintenance_in_tests",
  srcs = [ "maintenance_in_test.cc" ],
  deps = [
    "//lib/translator:maintenance_in_lib",
    "@googletest//:gtest_main"
  ]
)

cc_test(
    name = "inquiry_tests",
    srcs = ["inquiry_test.cc"],
    deps = [
        "//lib/translator:inquiry_lib",
        "@googletest//:gtest_main"
    ],
)

cc_test(
  name = "common_tests",
  srcs = [ "common_test.cc" ],
  deps = [
    "//lib/translator:common",
    "//lib:scsi_lib",
    "@googletest//:gtest_main"
  ]
)

cc_test(
  name = "translation_tests",
  srcs = [ "translation_test.cc" ],
  deps = [
    "//lib/translator:translation",
    "@googletest//:gtest_main"
  ]
)

cc_test(
  name = "report_luns_test",
  srcs = [ "report_luns_test.cc" ],
  deps = [
    "//lib/translator:report_luns_lib",
    "@googletest//:gtest_main"
  ]
)

cc_test(
  name = "status_test",
  srcs = [ "status_test.cc" ],
  deps = [
    "//lib/translator:status_lib",
    "@googletest//:gtest_main"
  ]
)

cc_test(
  name = "unmap_test",
  srcs = [ "unmap_test.cc" ],
  deps = [
    "//lib/translator:unmap_lib",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "mode_sense_test",
  srcs = [ "mode_sense_test.cc"],
  deps = [
    "//lib/translator:mode_sense_lib",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "read_tests",
  srcs = [ "read_test.cc" ],
  deps = [
    "//lib/translator:read_lib",
    "@googletest//:gtest_main"
  ]
)

cc_test(
  name = "request_sense_tests",
  srcs = [ "request_sense_test.cc" ],
  deps = [
    "//lib/translator:request_sense_lib",
    "@googletest//:gtest_main",
  ]
)

cc_test(
  name = "synchronize_cache_tests",
  srcs = [ "synchronize_cache_test.cc" ],
  deps = [
    "//lib/translator:synchronize_cache_lib",
    "@googletest//:gtest_main"
  ]
)

cc_test(
  name = "verify_tests",
  srcs = [ "verify_test.cc"],
  deps = [
    "//lib/translator:verify_lib",
    "@googletest//:gtest_main",
  ]
)

